name: passengers
description: A Flutter project for managing Umrah visa clients.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6

  # State Management
  provider: ^6.1.1

  # Local Storage
  shared_preferences: ^2.2.2

  # Files & Storage
  path_provider: ^2.1.1
  file_picker: ^8.1.4
  cross_file: ^0.3.4+2

  # Images & Media
  image_picker: ^1.0.4
  image: ^4.1.3
  flutter_image_compress: ^2.0.4
  cached_network_image: ^3.3.0

  # UI & Utils
  url_launcher: ^6.2.1
  flutter_spinkit: ^5.2.0
  intl: ^0.20.2

  # Security
  crypto: ^3.0.3

  # Timezone for notifications
  timezone: ^0.9.0

  # Localization
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files
  generate: false

  # Assets
  # assets:
  #   - images/

  # Fonts
  # fonts:
  #   - family: Cairo
  #     fonts:
  #       - asset: fonts/Cairo-Regular.ttf
  #       - asset: fonts/Cairo-Bold.ttf
  #         weight: 700